eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #?????hostname
    #    instance:
    #      hostname: client
    register-with-eureka: false
  #??????????????????
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
#server:
#  port: 8761
